learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
"""
Sets URL patterns for learning_logs app.
"""

from django.urls import path
from . import views


app_name = 'learning_logs'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    # Page with all the topics created by user.
    path('topics/', views.topics, name='topics'),
    # Page with all the entries for certain topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page with a form for creating new topic.
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page with a form for creating new entry for some topic.
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page with a form for editing existing entry for some topic.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""
Sets URL patterns for users app.
"""

from django.urls import path, include

from . import views


app_name = 'users'
urlpatterns = [
    # Django default authentication pages.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Topic(models.Model):
    """
    Topic being studied by user.
    """

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Returns string representation of a model."""
        return self.text


class Entry(models.Model):
    """
    Some info learned or saved by user on certain topic.
    """

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Returns string representation of a model."""
        return f"{self.text[:50]}..." if len(self.text) > 50 else self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from  django import forms

from.models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """Home page of learning_logs app."""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Shows all the topics created by user."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Shows all the entries for a certain topic."""
    topic = get_object_or_404(Topic, id=topic_id)

    check_topic_owner(request, topic)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Defines new topic."""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Defines new entry for a certain topic."""
    topic = get_object_or_404(Topic, id=topic_id)

    check_topic_owner(request, topic)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Page for editing existing entry."""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic

    check_topic_owner(request, topic)

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'form': form, 'topic': topic, 'entry': entry}
    return render(request, 'learning_logs/edit_entry.html', context)


def check_topic_owner(request, topic):
    """Checks if topic was created by current user."""
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Registers new user."""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Your Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark mb-4 border"
         style="background-color: #1d3557;">

        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h4><a style="color: #457b9d;" href="{% url 'learning_logs:topic' topic.id %}">
        {{ topic }}</a></h4>
{% endblock page_header %}

{% block content %}
    <h5>Edit entry:</h5>
    <form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}"
          class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button style="background-color: #457b9d;" name="submit"
                    class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <div class="jumbotron" style="background-color: #f1faee;">
        <h1 class="display-3" >Track your learning.</h1>

        <p class="lead">
            Create your own Learning Log. Write down interesting and important facts
            on the topic you are studying.
        </p>
        <p class="lead">Stay tuned for exploring new exciting things!</p>

        <a class="btn btn-lg btn-dark" style="background-color: #457b9d;"
           href="{% url 'users:register' %}"
           role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h4><a style="color: #457b9d;" href="{% url 'learning_logs:topic' topic.id %}">
        {{ topic }}</a></h4>
{% endblock page_header %}

{% block content %}
    <h5>Add a new entry:</h5>
    <form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button style="background-color: #457b9d;" name="submit"
                    class="btn btn-primary">Add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <h3>Add a new topic:</h3>
    <form method="post" action="{% url 'learning_logs:new_topic' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button style="background-color: #457b9d;" name="submit"
                    class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h3 style="color: #457b9d;">{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
                    edit entry</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>No entries for this topic added yet.</p>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1 style="color: #1d3557;">Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li><h3>
                <a style="color: #457b9d;" href="{% url 'learning_logs:topic' topic.id %}">
                    {{ topic }}</a>
            </h3></li>
        {% empty %}
        <li><h3>No topics added yet. Start learning right now!</h3></li>
        {% endfor %}
    </ul>

<h5><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h5>

{% endblock content %}